#!/usr/bin/env bash
#
# clean_smoke_outputs.sh — reclaim disk from disposable smoke/probe output dirs.
#
# The v2 workspace accumulates one-off `outputs/*smoke*` / `*probe*` / temp dirs
# from commit smokes, training smokes, perf smokes, and runtime probes. These are
# safe to delete (they are regenerated by the corresponding smoke commands and are
# git-ignored). Persistent artifacts (datasets, models, evaluations, inference_demo,
# manual_review, ore_pipeline_ui run history) are NEVER matched.
#
# Default is a DRY RUN: it prints what would be removed and the reclaimable size.
# Pass --force (or -f) to actually delete.
#
# Usage:
#   scripts/clean_smoke_outputs.sh            # dry run, show candidates + sizes
#   scripts/clean_smoke_outputs.sh --force    # delete the candidates
#
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUTS_DIR="$REPO_ROOT/outputs"

FORCE=0
for arg in "$@"; do
  case "$arg" in
    -f|--force) FORCE=1 ;;
    -h|--help)
      grep '^#' "$0" | sed 's/^# \{0,1\}//'
      exit 0 ;;
    *)
      echo "Unknown argument: $arg (use --force or --help)" >&2
      exit 2 ;;
  esac
done

if [[ ! -d "$OUTPUTS_DIR" ]]; then
  echo "No outputs/ directory at $OUTPUTS_DIR — nothing to do."
  exit 0
fi

# Glob patterns for disposable directories, relative to outputs/.
# Keep this list conservative and explicit.
PATTERNS=(
  '*smoke*'
  '*probe*'
  'pycache_tmp'
)

# Collect matching top-level directories (unique, sorted).
candidates=()
shopt -s nullglob
for pat in "${PATTERNS[@]}"; do
  for path in "$OUTPUTS_DIR"/$pat; do
    [[ -d "$path" ]] || continue
    candidates+=("$path")
  done
done
shopt -u nullglob

# De-duplicate.
if [[ ${#candidates[@]} -gt 0 ]]; then
  IFS=$'\n' candidates=($(printf '%s\n' "${candidates[@]}" | sort -u)); unset IFS
fi

if [[ ${#candidates[@]} -eq 0 ]]; then
  echo "No disposable smoke/probe directories found under outputs/."
  exit 0
fi

echo "Candidate directories under outputs/ (patterns: ${PATTERNS[*]}):"
for path in "${candidates[@]}"; do
  size="$(du -sh "$path" 2>/dev/null | cut -f1)"
  printf '  %-8s %s\n' "$size" "${path#"$REPO_ROOT"/}"
done

total="$(du -sch "${candidates[@]}" 2>/dev/null | tail -1 | cut -f1)"
echo "Total reclaimable: ${total}"

if [[ "$FORCE" -ne 1 ]]; then
  echo
  echo "Dry run — nothing deleted. Re-run with --force to delete the above."
  exit 0
fi

echo
echo "Deleting ${#candidates[@]} director$([[ ${#candidates[@]} -eq 1 ]] && echo y || echo ies)..."
for path in "${candidates[@]}"; do
  rm -rf "$path"
  echo "  removed ${path#"$REPO_ROOT"/}"
done
echo "Done. Reclaimed ~${total}."
